### ISSUE TITLE
Allow certain words?

### ISSUE THREAD

**Issue by Codeize** [vzhou842/profanity-check#31]
Sometimes the filter can be a tad excessive. I.E: I say damn, the filter is triggered. This should be customizable. Or what I recommend is setting up a 'level based filter' For example.. Level 1 - Low (F#@? gets deleted, and similar, not damn) and then something like Level 3 - Strict (Deletes all profanity, such as damn, sick, etc.)

**Comment by BradKML** [comment]
Because this library is model-based and does not rely on a wordlist? https://github.com/vzhou842/profanity-check#no-explicit-blacklist

**Comment by felixgao-0** [comment]
It could just check a list given and see if a word is on there. If its there then it will bypass all filters and it will be cleared.

**Comment by BradKML** [comment]
@FelixGao-discord "Model-Based" means that the library compresses the wordlist into a more generalized and fuzzy format using sub-patterns, and the process is irreversible. The only way to do what @Codeize said is something like having multiple wordlists of different strengths and multiple corresponding models to tune down its sensitivity.
