### ISSUE TITLE
suggestion: be able to specify which model is used

### ISSUE THREAD

**Issue by Jourdelune** [vzhou842/profanity-check#37]
Hello, it would be nice to be able to specify which model is used to add different languages etc...

**Comment by menkotoglou** [comment]
Could you please elaborate on your question? Can't really understand what you mean.

**Comment by BradKML** [comment]
There are other libraries with multilingual Profanity Lists.
- https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words
- https://github.com/words/cuss
- https://github.com/chucknorris-io/swear-words
- https://github.com/thisandagain/washyourmouthoutwithsoap

**Comment by menkotoglou** [comment]
Many thanks, @BrandonKMLee for moderating the issues and supporting.
