### ISSUE TITLE
How would one go in order to add spanish support?

### ISSUE THREAD

**Issue by zardilior** [vzhou842/profanity-check#5]

**Comment by vzhou842** [comment]
You'd need a labeled spanish dataset to train on, which unfortunately I don't have.

**Comment by zardilior** [comment]
@vzhou842 we have seen there are no good spanish profanity checkers available, we would be interested in generating that labeled spanish dataset to train on. How would this dataset be in order to be useful to you?

**Comment by vzhou842** [comment]
You'd just need to have a large size of examples of both profane spanish text and clean (not profane) spanish text. Ideally you'd probably want 100k+ examples.

**Comment by zardilior** [comment]
mmm.... If I make an open source list it might be possible

**Comment by fractefactos** [comment]
... That would be great.
