### ISSUE TITLE
setup.py sklearn reqt

### ISSUE THREAD

**Issue by bscully27** [vzhou842/profanity-check#7]
setup.py has, "scikit-learn==0.20.2"

at least change to greater than or equal:  scikit-learn>=0.20.2

**Comment by vshestopalov** [comment]
That's a good point, otherwise it's hard to use in env with another ML stuff.

**Comment by vzhou842** [comment]
That's fair @bscully27, would love a PR if you want to tackle it

**Comment by vchulski** [comment]
@vzhou842 To use scikit-learn of higher versions without warnings it's needed to re-train models and create new model and vectorizer dumps.

**Comment by vzhou842** [comment]
done #8
